// <auto-generated />
namespace Forum_Projekt.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Forum_ProjektDataContextForumDbConfiguration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Forum_ProjektDataContextForumDbConfiguration));
        
        string IMigrationMetadata.Id
        {
            get { return "201510281008201_Forum_Projekt.DataContext.ForumDb.Configuration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
